#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHIM="$ROOT/shims/ios/ZMRShim.swift"
UITEST="$ROOT/shims/ios/ZMRShimUITestCase.swift"

grep -q 'let value: String' "$SHIM"
grep -q 'struct ZMRShimViewport' "$SHIM"
grep -q 'static func viewport(app: XCUIApplication)' "$SHIM"
grep -q 'value: elementValue(element)' "$SHIM"
grep -q 'element.value' "$SHIM"
grep -q 'guard element.exists else' "$SHIM"
grep -q '"value": "Continue"' "$ROOT/shims/ios/protocol.md"
grep -q '"viewport": { "width": 390, "height": 844 }' "$ROOT/shims/ios/protocol.md"
grep -q 'hideKeyboard(app: app)' "$UITEST"
grep -q '"viewport": ZMRShim.viewport(app: app).json' "$UITEST"
grep -q 'case "viewport"' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "viewport command must not enumerate snapshot nodes" unless source.match?(/case "viewport":\s*return \[\s*"status": "ok",\s*"viewport": ZMRShim\.viewport\(app: app\)\.json\s*\]/m)' "$UITEST"
grep -q '"Done"' "$UITEST"
grep -q '"done"' "$UITEST"
grep -q '"Return"' "$UITEST"
grep -q 'resolveFastElement(selector: selector, app: app, preferredTypes: \[\])' "$UITEST"
grep -q 'resolveBroadElement(selector:' "$UITEST"
grep -q 'allDescendantQueries(app: app, type: .any).map { $0.matching(predicate) }' "$UITEST"
grep -q 'app.windows.descendants(matching: type)' "$SHIM"
grep -q '.other' "$SHIM"
grep -q 'identifier != %@' "$SHIM"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "snapshotQueries needs explicit default return" unless source.match?(/if type == \.other \{.*?return \[.*?\}\s*return \[/m)' "$SHIM"
grep -q 'app.windows.descendants(matching: type)' "$UITEST"
grep -q 'commandRequiresForeground' "$UITEST"
grep -q 'ensureAppForeground' "$UITEST"
grep -q 'app.activate()' "$UITEST"
grep -q '.runningForeground' "$UITEST"
grep -q 'acceptExpoDevClientDeepLink(' "$UITEST"
grep -q 'openedURL: command.url' "$UITEST"
grep -q 'Deep link received:' "$UITEST"
grep -q 'isExpoDevClientDeepLinkTarget(label:' "$UITEST"
grep -q 'label.contains("://")' "$UITEST"
grep -q 'resumeExpoDevClientHome(app: app)' "$UITEST"
grep -q 'Development servers' "$UITEST"
grep -q 'isExpoDevClientProjectTarget(label:' "$UITEST"
grep -q 'tapFirstMatchingExpoCandidate' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "Expo candidate queries must include targeted staticText fallback" unless source.include?("queries: [app.buttons, app.cells, app.staticTexts]")' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "Expo candidate helper must scan bounded matches, not only firstMatch" unless source.include?("for candidateIndex in 0..<6") && source.include?("matching.element(boundBy: candidateIndex)")' "$UITEST"
grep -q 'expoDevClientFallback' "$SHIM"
grep -q 'tapExpoDevClientDeepLinkCoordinateFallback' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "Expo fallback must search candidate rows even when the modal title is not queryable" unless source.include?("tapExpoDevClientDeepLinkCandidateFallback(app: app, predicate: predicate)")' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "Expo coordinate fallback must target the first app row in the full simulator frame" unless source.include?("CGVector(dx: 0.5, dy: 0.6)")' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); coordinate = source.index("if tapExpoDevClientDeepLinkCoordinateFallback(app: app)"); candidate = source.index("if tapExpoDevClientDeepLinkCandidateFallback(app: app, predicate: predicate)"); abort "Expo coordinate fallback must run before row candidate queries because the picker rows can be non-queryable" unless coordinate && candidate && coordinate < candidate' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); body = source[/private func tapExpoDevClientDeepLinkCoordinateFallback\(app: XCUIApplication\) -> Bool \{(.*?)\n    \}/m, 1] || ""; sleep_index = body.index("Thread.sleep(forTimeInterval: 1.5)"); tap_index = body.index("app.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.6)).tap()"); abort "Expo coordinate fallback must wait for the async picker before tapping" unless sleep_index && tap_index && sleep_index < tap_index' "$UITEST"
ruby -e 'source = File.read(ARGV.fetch(0)); abort "Expo coordinate fallback must be gated by custom non-dev-client URLs" unless source.include?("isCustomSchemeURL(openedURL)") && source.include?("!isExpoDevClientURL(openedURL)")' "$UITEST"
if grep -q 'app.staticTexts.allElementsBoundByIndex' "$UITEST"; then
  echo "Expo dev-client helpers must not enumerate staticTexts by index; it can crash XCTest when the screen mutates" >&2
  exit 1
fi
