#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZMR="$ROOT/zig-out/bin/zmr"

OUTPUT="$("$ZMR" schemas --json)"
grep -q '"ok":true' <<< "$OUTPUT"
grep -q '"count":26' <<< "$OUTPUT"
grep -q '"name":"scenario"' <<< "$OUTPUT"
grep -q '"path":"schemas/scenario.schema.json"' <<< "$OUTPUT"
grep -q '"id":"https://zmr.dev/schemas/scenario.schema.json"' <<< "$OUTPUT"
grep -q '"name":"zmr-config"' <<< "$OUTPUT"
grep -q '"name":"doctor-output"' <<< "$OUTPUT"
grep -q '"name":"devices-output"' <<< "$OUTPUT"
grep -q '"name":"validate-output"' <<< "$OUTPUT"
grep -q '"name":"version-output"' <<< "$OUTPUT"
grep -q '"name":"capabilities-output"' <<< "$OUTPUT"
grep -q '"path":"schemas/capabilities-output.schema.json"' <<< "$OUTPUT"
grep -q '"name":"semantic-snapshot"' <<< "$OUTPUT"
grep -q '"path":"schemas/semantic-snapshot.schema.json"' <<< "$OUTPUT"
grep -q '"name":"explain-output"' <<< "$OUTPUT"
grep -q '"name":"run-output"' <<< "$OUTPUT"
grep -q '"name":"import-output"' <<< "$OUTPUT"
grep -q '"name":"inspect-output"' <<< "$OUTPUT"
grep -q '"path":"schemas/inspect-output.schema.json"' <<< "$OUTPUT"
grep -q '"name":"discover-output"' <<< "$OUTPUT"
grep -q '"path":"schemas/discover-output.schema.json"' <<< "$OUTPUT"
grep -q '"name":"explore-output"' <<< "$OUTPUT"
grep -q '"path":"schemas/explore-output.schema.json"' <<< "$OUTPUT"
grep -q '"name":"draft-output"' <<< "$OUTPUT"
grep -q '"path":"schemas/draft-output.schema.json"' <<< "$OUTPUT"
grep -q '"name":"release-manifest"' <<< "$OUTPUT"
grep -q '"path":"schemas/release-manifest.schema.json"' <<< "$OUTPUT"
grep -q '"name":"run-summary"' <<< "$OUTPUT"
grep -q '"path":"schemas/run-summary.schema.json"' <<< "$OUTPUT"
grep -q '"name":"bootstrap-event"' <<< "$OUTPUT"
grep -q '"path":"schemas/bootstrap-event.schema.json"' <<< "$OUTPUT"
grep -q '"name":"release-readiness-output"' <<< "$OUTPUT"
grep -q '"path":"schemas/release-readiness-output.schema.json"' <<< "$OUTPUT"
grep -q '"name":"schemas-output"' <<< "$OUTPUT"
