const std = @import("std");

pub const PublicError = struct {
    code: []const u8,
    message: []const u8,
};

pub fn classify(err: anyerror) PublicError {
    return switch (err) {
        error.MissingScenarioPath => .{ .code = "cli.missing_scenario", .message = "missing scenario path" },
        error.MissingDeviceSerial => .{ .code = "cli.missing_device", .message = "missing device serial" },
        error.MissingTraceDir => .{ .code = "cli.missing_trace_dir", .message = "missing trace directory" },
        error.MissingReportInput => .{ .code = "cli.missing_report_input", .message = "missing report input path" },
        error.MissingReportOutput => .{ .code = "cli.missing_report_output", .message = "missing report output path" },
        error.MissingDraftOut => .{ .code = "cli.missing_draft_out", .message = "missing draft output path" },
        error.MissingDiscoverOut => .{ .code = "cli.missing_discover_out", .message = "missing discover output path" },
        error.MissingJUnitOutput => .{ .code = "cli.missing_junit_output", .message = "missing JUnit output path" },
        error.MissingTraceBundleOutput => .{ .code = "cli.missing_trace_bundle_output", .message = "missing trace bundle output path" },
        error.MissingTestWorkspace => .{ .code = "cli.missing_test_workspace", .message = "missing test workspace path" },
        error.MissingTestWorkers => .{ .code = "cli.missing_test_workers", .message = "missing worker count" },
        error.MissingTestRetries => .{ .code = "cli.missing_test_retries", .message = "missing retry count" },
        error.MissingTestOutputDir => .{ .code = "cli.missing_test_output_dir", .message = "missing test output directory" },
        error.MissingTestPlatform => .{ .code = "cli.missing_test_platform", .message = "missing test platform" },
        error.MissingTestDevice => .{ .code = "cli.missing_test_device", .message = "missing test device serial" },
        error.MissingTestAppId => .{ .code = "cli.missing_test_app_id", .message = "missing test app id" },
        error.MissingTestAdb => .{ .code = "cli.missing_test_adb", .message = "missing test adb path" },
        error.MissingTestXcrun => .{ .code = "cli.missing_test_xcrun", .message = "missing test xcrun path" },
        error.MissingTestAndroidShim => .{ .code = "cli.missing_test_android_shim", .message = "missing Android shim path" },
        error.MissingTestIosShim => .{ .code = "cli.missing_test_ios_shim", .message = "missing iOS shim path" },
        error.MissingRecordTraceDir => .{ .code = "cli.missing_record_trace_dir", .message = "missing record trace directory" },
        error.MissingRecordTransport => .{ .code = "cli.missing_record_transport", .message = "missing record transport" },
        error.MissingRecordPort => .{ .code = "cli.missing_record_port", .message = "missing record port" },
        error.MissingAppId => .{ .code = "cli.missing_app_id", .message = "missing app id" },
        error.AppIdRequired => .{ .code = "init.app_id_required", .message = "app id is required and could not be derived" },
        error.MissingAdbPath => .{ .code = "cli.missing_adb_path", .message = "missing adb path" },
        error.MissingXcrunPath => .{ .code = "cli.missing_xcrun_path", .message = "missing xcrun path" },
        error.MissingZigPath => .{ .code = "cli.missing_zig_path", .message = "missing zig path" },
        error.MissingPlatform => .{ .code = "cli.missing_platform", .message = "missing platform" },
        error.unknownCommand => .{ .code = "cli.unknown_command", .message = "unknown command" },
        error.unknownFlag => .{ .code = "cli.unknown_flag", .message = "unknown flag" },
        error.MissingParam => .{ .code = "cli.missing_param", .message = "missing parameter" },
        error.FileNotFound => .{ .code = "scenario.file_not_found", .message = "scenario file was not found" },
        error.SemanticSnapshotMissing => .{ .code = "draft.no_snapshot", .message = "no semantic snapshot was found in the trace" },
        error.InvalidTraceManifest => .{ .code = "trace.invalid_manifest", .message = "trace manifest is invalid" },
        error.InvalidSemanticSnapshot => .{ .code = "trace.invalid_semantic_snapshot", .message = "semantic snapshot is invalid" },
        error.UnsupportedPlatform => .{ .code = "cli.unsupported_platform", .message = "unsupported platform" },
        error.UnsupportedTransport => .{ .code = "cli.unsupported_transport", .message = "unsupported transport" },
        error.InvalidTestWorkers => .{ .code = "cli.invalid_test_workers", .message = "worker count is invalid" },
        error.InvalidTestRetries => .{ .code = "cli.invalid_test_retries", .message = "retry count is invalid" },
        error.InvalidTestPlatform => .{ .code = "cli.invalid_test_platform", .message = "test platform is invalid" },
        error.ConflictingShardModes => .{ .code = "cli.conflicting_shard_modes", .message = "shard modes are mutually exclusive" },
        error.InvalidRecordTransport => .{ .code = "cli.invalid_record_transport", .message = "record transport is invalid" },
        error.InvalidRecordPort => .{ .code = "cli.invalid_record_port", .message = "record port is invalid" },
        error.ScenarioMustBeObject,
        error.UnknownScenarioField,
        error.UnknownScenarioStepField,
        error.ScenarioMissingSteps,
        error.ScenarioStepsMustBeArray,
        error.StepMustBeObject,
        error.StepMissingAction,
        error.StepActionMustBeString,
        error.unknownAction,
        error.unknownScenarioAction,
        error.unknownScrollDirection,
        error.StepMissingUrl,
        error.StepMissingText,
        error.StepMissingKey,
        error.StepMissingX1,
        error.StepMissingY1,
        error.StepMissingX2,
        error.StepMissingY2,
        error.StepMissingLatitude,
        error.StepMissingLongitude,
        error.StepMissingPermissions,
        error.StepMissingOrientation,
        error.StepOrientationMustBeString,
        error.StepOrientationInvalid,
        error.StepLaunchArgumentsMustBeObject,
        error.StepLaunchArgumentNameEmpty,
        error.StepLaunchArgumentValueUnsupported,
        error.StepPermissionsMustBeArray,
        error.StepPermissionMustBeString,
        error.StepLatitudeMustBeNumber,
        error.StepLongitudeMustBeNumber,
        error.StepLatitudeOutOfRange,
        error.StepLongitudeOutOfRange,
        error.RequiredFieldMustBeNumber,
        error.ScenarioBindingsMustBeObject,
        error.ScenarioBindingValueMustBeString,
        error.ScenarioLabelsMustBeArray,
        error.ScenarioLabelMustBeString,
        error.ScenarioSourceMustBeObject,
        error.ScenarioSourceMissingFile,
        error.ScenarioSourceFileMustBeString,
        error.ScenarioSourceMissingLine,
        error.ScenarioSourceMissingColumn,
        error.ScenarioSourceLineInvalid,
        error.ScenarioSourceColumnInvalid,
        error.StepBlockMissingSteps,
        error.StepBlockStepsMustBeArray,
        error.OptionalFieldMustBeString,
        error.OptionalStepMissingStep,
        error.RepeatOutOfRange,
        error.RetryOutOfRange,
        => .{ .code = "scenario.invalid", .message = "scenario is invalid" },
        error.SelectorMustNotBeEmpty,
        error.UnknownSelectorField,
        error.MissingSelector,
        error.StepMissingSelector,
        error.MissingSelectors,
        error.StepMissingSelectors,
        error.SelectorsMustBeArray,
        error.SelectorsMustNotBeEmpty,
        error.SelectorMustBeObject,
        error.SelectorFieldMustBeString,
        error.SelectorFieldMustBeBool,
        error.SelectorIndexOutOfRange,
        error.SelectorPointMustBeObject,
        error.UnknownSelectorPointField,
        error.SelectorPointMissingCoordinate,
        error.SelectorPointCoordinateMustBeInteger,
        => .{ .code = "selector.invalid", .message = "selector is invalid" },
        error.NoTestScenarios => .{ .code = "test.no_scenarios", .message = "no canonical scenarios were found in the workspace" },
        error.NoReadyTestDevice => .{ .code = "test.no_ready_device", .message = "no ready device matched the test request" },
        error.TestRunFailed => .{ .code = "test.failed", .message = "one or more test scenarios failed" },
        error.WaitTimeout => .{ .code = "runner.wait_timeout", .message = "wait timed out" },
        error.AssertionFailed => .{ .code = "runner.assertion_failed", .message = "assertion failed" },
        error.SelectorNotFound => .{ .code = "runner.selector_not_found", .message = "selector not found" },
        error.CommandFailed => .{ .code = "device.command_failed", .message = "device command failed" },
        error.CommandTimedOut => .{ .code = "device.command_timed_out", .message = "device command timed out" },
        error.UnsupportedDeviceCapability => .{ .code = "device.unsupported_capability", .message = "device capability is unsupported" },
        error.AppLaunchActivityNotFound => .{ .code = "app.launch_activity_not_found", .message = "could not resolve the Android launch activity for launch arguments" },
        error.IosXCTestShimRequired => .{ .code = "ios.xctest_shim_required", .message = "iOS selector interaction requires the XCTest shim" },
        error.IosXCTestShimResponseTimedOut => .{ .code = "ios.xctest_shim_response_timeout", .message = "iOS XCTest shim response timed out" },
        error.IosXCTestShimStartTimedOut => .{ .code = "ios.xctest_shim_start_timeout", .message = "iOS XCTest shim server startup timed out" },
        error.IosXCTestShimBuildTimedOut => .{ .code = "ios.xctest_shim_build_timeout", .message = "iOS XCTest shim build timed out" },
        error.IosXCTestShimServerExited => .{ .code = "ios.xctest_shim_server_exited", .message = "iOS XCTest shim server exited" },
        else => .{ .code = "internal.error", .message = @errorName(err) },
    };
}
